### ISSUE TITLE
Remaining Card Detection

### ISSUE THREAD

**Issue by DannieBGoode** [DoctorMcKay/Steam-Card-Farmer#10]
When closing the program, if only 1 card was missing for the current game. Next time the program is opened it will think all cards have already been farmed for that game (eventhough there's still 1 missing).

**Comment by Avaray** [comment]
Same issue here.
The game that I had problem was "X-Blades" (11 cards total).

**Comment by ric20007** [comment]
This change should fix it, there was a question mark missing
https://github.com/DoctorMcKay/Steam-Card-Farmer/pull/12

**Comment by DoctorMcKay** [comment]
Fixed in 1.5.2.
