### ISSUE TITLE
Node Steam update

### ISSUE THREAD

**Issue by gregduc** [DoctorMcKay/Steam-Card-Farmer#11]
Hi guy,
You need to update your code. Node steam module was updated

**Comment by DoctorMcKay** [comment]
I'm sorry, what?

**Comment by gregduc** [comment]
In your code, you use:
``` javascript
client.on('webSessionID', function(sessionID) {
	g_HasWebSessionID = true;
``` 

It was removed 4 months ago:
https://github.com/seishun/node-steam/releases/tag/v1.0.0

**Comment by DoctorMcKay** [comment]
It's using my special fork of version 0.6.8.

**Comment by gregduc** [comment]
Haha, that's work! ;) (I was just an advice ;) )
