### ISSUE TITLE
Not idleing games

### ISSUE THREAD

**Issue by Alb3r** [DoctorMcKay/Steam-Card-Farmer#28]
Hello. First of all I'd want to make clear that I'm completely new to this and that I have no idea if I'm doing something wrong or not. That said, here's my problem:
[http://i.imgur.com/KTTldZM.jpg?1](url)

As you can see in the image, the program has detected 0 apps, but if you chek my Steam profile (http://steamcommunity.com/id/alb3rb3r/) you can see that I own 9 games. Why is this happening? Is there any solution?

Thanks in advance. If you need any other details, I will submit them.

PD: As I've read in the README.TXT, I must include npm.debug.txt here, so there it goes:

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'test' ]
2 info using npm@3.10.10
3 info using node@v7.3.0
4 verbose stack Error: ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
5 verbose cwd C:\Windows\system32
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "test"
8 error node v7.3.0
9 error npm  v3.10.10
10 error path C:\Windows\system32\package.json
11 error code ENOENT
12 error errno -4058
13 error syscall open
14 error enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
15 error enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]

**Comment by DoctorMcKay** [comment]
That means that it found no games with remaining card drops on your account. Please check https://steamcommunity.com/my/badges. Do you see any games that have card drops left?

**Comment by RedSparr0w** [comment]
Looks like you did everything correctly 😃 
 just looks like there are no card drops remaining as said above.

**Comment by Alb3r** [comment]
> That means that it found no games with remaining card drops on your account. Please check https://steamcommunity.com/my/badges. Do you see any games that have card drops left?

Ah yes, as you said there are no card drops remaining. Thanks for the quick response.
