### ISSUE TITLE
0 card drops remaining across 0 apps (Page 1)

### ISSUE THREAD

**Issue by whatugonnado** [DoctorMcKay/Steam-Card-Farmer#32]
Why doesn't it search for Page 2 or more?

**Comment by whatugonnado** [comment]
https://github.com/DoctorMcKay/Steam-Card-Farmer/blob/1868c9fb7052b99f918ec560945682c203c92250/farmer.js#L378
code seems to check, but not working

**Comment by whatugonnado** [comment]
was using cli version in (bash on ubuntu on) windows

**Comment by RedSparr0w** [comment]
From #25 

Steam has recently limited the badges page to 150 apps per page,

search for:
 `$_('.badge_row').length == 250`
inside of `farmer.js`
and replace it with:
`$_('.badge_row').length == 150`

That should check [your first page of badges](https://steamcommunity.com/my/badges/?p=1) then once that page is done it will move onto the next page until all cards have dropped
