### ISSUE TITLE
CAPTCHAs.IO Integration

### ISSUE THREAD

**Issue by articlefr** [DoctorMcKay/Steam-Card-Farmer#36]
Hi,

I'd like to ask support for integration of https://captchas.io/ captcha solving service.

Thanks!
Glenn Prialde

**Comment by DoctorMcKay** [comment]
For what purpose>

**Comment by Aidoboy** [comment]
He's got to make the cold, hard cash somehow.

**Comment by DoctorMcKay** [comment]
Ah, I see. You're just a spammer. Blocked.
