### ISSUE TITLE
env: node/r: no such file or directory

### ISSUE THREAD

**Issue by dragonbanshee** [DoctorMcKay/Steam-Card-Farmer#5]
I get the error `env: node/r: no such file or directory` when trying to run this on Mac OSX Yosemite. This happens when I type `steamcardfarmer` in the command line, regardless if I use a username and password or not.

**Comment by DoctorMcKay** [comment]
Seems to be a consequence of Windows-style line endings.

**Comment by DoctorMcKay** [comment]
Give 1.3.1 a shot.

**Comment by dragonbanshee** [comment]
Getting the same error still.

**Comment by nzero** [comment]
I was having kind of the same thing on linux

> $ steamcardfarmer 
> /usr/bin/env: node: No such file or directory

I followed the instructions [here](http://javascript.tutorialhorizon.com/2015/03/01/troubleshooting-usrbinenv-node-no-such-file-or-directory/] and created a symbolic link "node" in /usr/bin to the file /usr/bin/nodejs

Now it is working

> $ steamcardfarmer 
> prompt: username:
