### ISSUE TITLE
Steam Sales

### ISSUE THREAD

**Issue by Avaray** [DoctorMcKay/Steam-Card-Farmer#7]
You app is trying to drop cards from summer sale.
Im not sure, but maybe it will be easy to do for you:

Way 1 - Give app possibility to check badge names.
If badge name contain strings like "winter sale", "summer sale", etc. then app will ignore this badge.

Way 2 - Give possibility to create blacklist based on game ID (steam sales have ID).

**Comment by DoctorMcKay** [comment]
Fixed in v1.4.0.

**Comment by Avaray** [comment]
Yeah, It works! Great job :)
